import uuid
import random
from datetime import datetime, timedelta

try:
    from faker import Faker
except ImportError:
    print("Please install faker first: pip install faker")
    exit(1)

try:
    from passlib.context import CryptContext
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
except ImportError:
    print("Please install passlib and bcrypt first: pip install passlib bcrypt")
    exit(1)

fake = Faker()

def escape_sql_string(value):
    if value is None:
        return 'NULL'
    if isinstance(value, str):
        # Escape single quotes
        escaped = value.replace("'", "''")
        return f"'{escaped}'"
    return str(value)

def format_date(dt):
    if dt is None:
        return 'NULL'
    return f"'{dt.strftime('%Y-%m-%d')}'"

def format_datetime(dt):
    if dt is None:
        return 'NULL'
    return f"'{dt.strftime('%Y-%m-%d %H:%M:%S%z')}'"

def format_bool(b):
    return 'true' if b else 'false'

def generate_seed_sql(num_users=20, num_doctors=5, num_patients=50, num_runs_per_patient=2):
    sql = []
    
    sql.append("-- Fake Data Seed Script generated by seed_data.py")
    sql.append("BEGIN;\n")
    
    users = []
    doctors = []
    patients = []
    runs = []
    
    # 1. Generate Users (Admins, Doctors, Patients)
    for _ in range(num_users):
        user_id = str(uuid.uuid4())
        role = random.choice(['admin', 'doctor', 'patient'])
        raw_password = fake.password(length=12)
        hashed_password = pwd_context.hash(raw_password)
        
        users.append({
            'user_id': user_id,
            'username': fake.user_name(),
            'email': fake.email(),
            'password_hash': hashed_password,
            'role': role
        })
        
        sql.append(
            f"-- Login -> Email: {users[-1]['email']} | Password: {raw_password}\n"
            f"INSERT INTO users (user_id, username, email, password_hash, role) "
            f"VALUES ('{user_id}', {escape_sql_string(users[-1]['username'])}, {escape_sql_string(users[-1]['email'])}, '{hashed_password}', '{role}');"
        )
        
    sql.append("\n-- Generate Doctors")
    doctor_users = [u for u in users if u['role'] == 'doctor']
    for du in doctor_users:
        doctor_id = str(uuid.uuid4())
        doctors.append({'doctor_id': doctor_id, 'user_id': du['user_id']})
        sql.append(
            f"INSERT INTO doctors (doctor_id, user_id, full_name, specialisation, qualification, registration_no) "
            f"VALUES ('{doctor_id}', '{du['user_id']}', {escape_sql_string(fake.name())}, 'Cardiology', 'MBBS, MD', {escape_sql_string(fake.ean(length=8))});"
        )
        
    sql.append("\n-- Generate Patients")
    patient_users = [u for u in users if u['role'] == 'patient']
    if not doctor_users:
        # Fallback if no doctors generated by random chance
        doctor_users = [users[0]]
        doctors = [{'doctor_id': str(uuid.uuid4()), 'user_id': users[0]['user_id']}]
        
    for pu in patient_users:
        patient_id = str(uuid.uuid4())
        primary_doctor_id = random.choice(doctors)['doctor_id']
        patients.append({'patient_id': patient_id, 'user_id': pu['user_id'], 'primary_doctor_id': primary_doctor_id})
        
        dob = fake.date_of_birth(minimum_age=18, maximum_age=90)
        gender = random.choice(['Male', 'Female', 'Other'])
        blood_group = random.choice(['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'])
        
        sql.append(
            f"INSERT INTO patients (patient_id, user_id, full_name, date_of_birth, gender, blood_group, primary_doctor_id, city, smoker, known_diabetes, known_hypertension) "
            f"VALUES ('{patient_id}', '{pu['user_id']}', {escape_sql_string(fake.name())}, '{dob.strftime('%Y-%m-%d')}', '{gender}', '{blood_group}', '{primary_doctor_id}', {escape_sql_string(fake.city())}, {format_bool(fake.boolean())}, {format_bool(fake.boolean())}, {format_bool(fake.boolean())});"
        )
        
    sql.append("\n-- Generate Diagnostic Runs, Vitals & Insights")
    for p in patients:
        for _ in range(num_runs_per_patient):
            run_id = str(uuid.uuid4())
            health_score = round(random.uniform(40.0, 95.0), 2)
            tier = random.choice(['Low', 'Medium', 'High', 'Critical'])
            
            sql.append(
                f"INSERT INTO diagnostic_runs (run_id, patient_id, doctor_id, health_score, risk_tier, heart_risk_pct, diabetes_risk_pct) "
                f"VALUES ('{run_id}', '{p['patient_id']}', '{p['primary_doctor_id']}', {health_score}, '{tier}', {round(random.uniform(0, 100), 2)}, {round(random.uniform(0, 100), 2)});"
            )
            
            # Vitals
            vitals_id = str(uuid.uuid4())
            sql.append(
                f"INSERT INTO patient_vitals (vitals_id, run_id, patient_id, blood_pressure_sys, blood_pressure_dia, heart_rate, bmi) "
                f"VALUES ('{vitals_id}', '{run_id}', '{p['patient_id']}', {random.randint(110, 160)}, {random.randint(70, 100)}, {random.randint(60, 100)}, {round(random.uniform(18.5, 35.0), 2)});"
            )
            
            # AI Insights
            insight_id = str(uuid.uuid4())
            sql.append(
                f"INSERT INTO ai_insights (insight_id, run_id, feature_name, shap_value, rank_position) "
                f"VALUES ('{insight_id}', '{run_id}', 'Age', {round(random.uniform(0.1, 1.5), 3)}, 1);"
            )
            
    sql.append("\nCOMMIT;")
    
    return "\n".join(sql)

if __name__ == "__main__":
    print("Generating fake SQL data...")
    sql_script = generate_seed_sql()
    output_path = 'seed_fake_data.sql'
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(sql_script)
    print(f"Success! Run the generated script via: psql -d <dbname> -f {output_path}")
